#
# UI

[app]
title = "SIRIUS"
href = "https://site.unibo.it/patrimonioculturalearischio/en/risk-atlas/explore-the-atlas-1"

    [app.nav_panel_01]
    title = "Risk Atlas"
    value_boxes = [
        "Object at highest risk",
        "Dominant risk on average",
        "Numbers of objects affected"
    ]

    [app.nav_panel_02]
    title = "Data"

#
# MAP

[map]
zoom = 14
latitude = 44.4183598
longitude = 12.2035294
popup_content = """
    <div class="card" style="width: 500px;">
        <div class="card-body">
            <h5 class="card-title">{row['label']}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{row['alt_label']}</h6>
            <div class="card-text">
                <dl class="row">
                    <dt class="col-sm-3">Description</dt>
                    <dd class="col-sm-9">{row['description']}</dd>
                    <dt class="col-sm-3">Inception</dt>
                    <dd class="col-sm-9">{row['date_created']}</dd>
                    <dt class="col-sm-3">Risk 1</dt>
                    <dd class="col-sm-9" 
                    data-id="risk1" 
                    data-value="{row['risk1']}">{row['risk1']}</dd>
                    <dt class="col-sm-3">Risk 2</dt>
                    <dd class="col-sm-9" 
                    data-id="risk2" 
                    data-value="{row['risk2']}">{row['risk2']}</dd>
                    <dt class="col-sm-3">Risk 3</dt>
                    <dd class="col-sm-9" 
                    data-id="risk3" 
                    data-value="{row['risk3']}">{row['risk3']}</dd>
                    <dt class="col-sm-3">Risk 4</dt>
                    <dd class="col-sm-9" 
                    data-id="risk4" 
                    data-value="{row['risk4']}">{row['risk4']}</dd>
                </dl>
            </div>
            <a href="https://www.wikidata.org/wiki/{row['id']}" target="_blank" class="card-link">Wikidata</a>
            <a href="{row['official_site']}" target="_blank" class="card-link">Official site</a>
            <a href="https://viaf.org/viaf/{row['viaf']}/" target="_blank" class="card-link">VIAF</a>
        </div>
    </div>
    """

    [map.legend]
    title = "Legend"

        [map.legend.color]
        low = "green"
        medium = "orange"
        high = "red"
        neutral = "grey"
        
        [map.legend.value]
        low = 1
        medium = 5
        high = 10

        [map.legend.text]
        low = "Low: between"
        medium = "Medium: between"
        high = "High: beyond"


#
# ENTITY DATA
[entity]
entities = [
    "Q721817",
    "Q644288",
    "Q1256487"
]


#
# GEOGRAPHIC DATA
[geo]
base_folder = "data/polygons"


#
# RISKS
[risk]
risks = [
    "Earthquake",
    "Flood",
    ]

    [risk.1]
    name = "Earthquake"
    path = "data/polygons/earthquake/Carta_della_subsidenza.shp"
    heading = "risk1"
    fill_color = "brown"
    api_service = "https://dati.arpae.it/it/api/3/action/package_show?id="
    id = "arpa_acq_sott_basea2"

    [risk.2]
    name = "Flood"
    path = "data/polygons/flood/MS23_Instab_GBE.shp"
    heading = "risk2"
    fill_color = "blue"
    api_service = "https://datacatalog.regione.emilia-romagna.it/catalogCTA/api/3/action/package_show?id="
    id = "carta-della-subsidenza-2011-2016"

