#
# UI

[app]
title = "SIRIUS"
href = "https://site.unibo.it/patrimonioculturalearischio/en/risk-atlas/explore-the-atlas-1"

    [app.nav_panel_01]
    title = "Risk Atlas"
    value_boxes = [
        "Object at highest risk",
        "Dominant risk on average",
        "Numbers of objects affected"
    ]

    [app.nav_panel_02]
    title = "Data"

#
# MAP

[map]
zoom = 14
latitude = 44.4183598
longitude = 12.2035294
popup_content = """
    <div class="card" style="width: 500px;">
        <div class="card-body">
            <h5 class="card-title">{row['label']}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{row['alt_label']}</h6>
            <div class="card-text">
                <dl class="row">
                    <dt class="col-sm-3">Description</dt>
                    <dd class="col-sm-9">{row['description']}</dd>
                    <dt class="col-sm-3">Inception</dt>
                    <dd class="col-sm-9">{row['date_created']}</dd>
                    <dt class="col-sm-3">Risk 1</dt>
                    <dd class="col-sm-9" 
                    data-id="risk1" 
                    data-value="{row['risk1']}">{row['risk1']}</dd>
                    <dt class="col-sm-3">Risk 2</dt>
                    <dd class="col-sm-9" 
                    data-id="risk2" 
                    data-value="{row['risk2']}">{row['risk2']}</dd>
                    <dt class="col-sm-3">Risk 3</dt>
                    <dd class="col-sm-9" 
                    data-id="risk3" 
                    data-value="{row['risk3']}">{row['risk3']}</dd>
                    <dt class="col-sm-3">Risk 4</dt>
                    <dd class="col-sm-9" 
                    data-id="risk4" 
                    data-value="{row['risk4']}">{row['risk4']}</dd>
                </dl>
            </div>
            <a href="https://www.wikidata.org/wiki/{row['id']}" target="_blank" class="card-link">Wikidata</a>
            <a href="{row['official_site']}" target="_blank" class="card-link">Official site</a>
            <a href="https://viaf.org/viaf/{row['viaf']}/" target="_blank" class="card-link">VIAF</a>
        </div>
    </div>
    """

    [map.legend]
    title = "Legend"

        [map.legend.color]
        low = "green"
        medium = "orange"
        high = "red"
        neutral = "grey"
        
        [map.legend.value]
        low = 1
        medium = 5
        high = 10

        [map.legend.text]
        low = "Low: between"
        medium = "Medium: between"
        high = "High: beyond"


#
# ENTITY DATA
[entity]
entities = [
    "Q721817",
    "Q644288",
    "Q1256487"
]

endpoint_url = "https://query.wikidata.org/sparql"

user_agent = "WDQS-example Python/{sys.version_info[0]}.{sys.version_info[1]}"

query = """
    SELECT ?entity ?label ?description (SAMPLE(?latitude) AS ?latitude) (SAMPLE(?longitude) AS ?longitude) ?official_site ?viaf 
    WHERE {
        VALUES_CLAUSE
        
        ?entity rdfs:label ?label .
        FILTER (LANG(?label) = "en")

        OPTIONAL { 
            ?entity skos:altLabel ?alt_label .
            FILTER (LANG(?alt_label) = "it") 
        }
        OPTIONAL { 
            ?entity p:P625 ?coordinate .
            ?coordinate psv:P625 ?coordinateValue .
            ?coordinateValue wikibase:geoLatitude ?latitude .
            ?coordinateValue wikibase:geoLongitude ?longitude .
        }
        OPTIONAL { 
            ?entity p:P571 ?inception .
            ?inception psv:P571 ?inceptionValue .
            ?inceptionValue wikibase:timeValue ?date_created .
        }
        OPTIONAL { ?entity wdt:P856 ?official_site }
        OPTIONAL { ?entity wdt:P214 ?viaf }
    } 
    GROUP BY ?entity ?label ?description ?official_site ?viaf
    """
#
# VOCABULARY
[vocabulary]
    [observation_types]
        Description = "http://vocab.getty.edu/page/aat/300435416"
        Measurement = "http://vocab.getty.edu/page/aat/300435430"
        Condition = "http://vocab.getty.edu/page/aat/300435425"
        Location = "http://vocab.getty.edu/page/aat/300435449"
        Diagnosis = "http://vocab.getty.edu/page/aat/300137593"
        Status = "http://vocab.getty.edu/page/aat/300438433"
        Budget = "http://vocab.getty.edu/page/aat/300027514"

    #[concepts]
    #contexts = {
    #    "Physical context": "XXX",
    #    "Social context": "XXX",
    #    "Economic context": "XXX",
    #    "Political context": "XXX",
    #   "Legal context": "XXX",
    #    "Administrative context": "XXX"
    #}
    #agents = {
    #    "Physical forces": "XXX",
    #    "Vandalism": "XXX",
    #    "Fire": "XXX",
    #    "Water": "XXX",
    #    "Pests": "XXX",
    #    "Pollutants": "XXX",
    #    "Light": "XXX",
    #    "Temperature": "XXX",
    #    "Humidity": "XXX",
    #    "Dissociation": "XXX",
    #}
    #scores = {
    #    "A-Score": "XXX",
    #    "B-Score": "XXX",
    #    "C-Score": "XXX",
    #    "MR-Score": "XXX"
    #}
    #frequencies = {
    #    "Rare": "XXX",
    #    "Common": "XXX", 
    #    "Cumulative": "XXX"
    #}
    #layers = {
    #    "Region": "XXX",
    #    "Site": "XXX",
    #    "Building": "XXX"
    #}
    #stages = {
    #    "Avoid": "XXX",
    #    "Block": "XXX",
    #    "Detect": "XXX",
    #    "Respond": "XXX",
    #    "Treat": "XXX"
    #}

#
# GEOGRAPHIC DATA
[geo]

    [geo.1]
    name = "Hydrogeo"
    color = "blue"
    path = "data/16_21_poligoni_class2_E32/16_21_poligoni_class2_E32.shp"
    risks = [
        "risk.1"
    ]

    [geo.2]
    name = "Subsidence"
    color = "brown"
    path = "data/sub2011-2016/sub_2011-2016.shp"
    risks = [
        "risk.2"
    ]


#
# RISKS
[risk]
api_service = "http://framelab.unibo.it/omeka/api"
vocabulary = "https://www.wikidata.org/wiki/"
probable_type = "Q226995"                   # prendi valore di tipo https://www.wikidata.org/wiki/Q226995
magnitude_observation_type = "Q2154759"     # riferito da observation di tipo https://www.wikidata.org/wiki/Q2154759
analysis_type = "Q217602"                   # assegnate da attività di tipo https://www.wikidata.org/wiki/Q217602
                                            # che assegnano a oggetto con quell'ID (punto di contatto)


risks = [
    "Earthquake",
    "Flood",
    ]

    [risk.1]
    name = "Earthquake"
    heading = "risk1"                                       # punto di contatto tra geo e dati rischio
    #fill_color = "brown"
    #api_service = "https://dati.arpae.it/it/api/3/action/package_show?id="
    #id = "arpa_acq_sott_basea2"

    [risk.2]
    name = "Flood"
    heading = "risk2"                                       # punto di contatto tra geo e dati rischio
    #fill_color = "blue"
    #api_service = "https://datacatalog.regione.emilia-romagna.it/catalogCTA/api/3/action/package_show?id="
    #id = "carta-della-subsidenza-2011-2016"

